import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layout from "@/layouts";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <AntdRegistry>{children}</AntdRegistry>
        </Layout>
      </body>
    </html>
  );
}
